"""
Chat API Router
===============
All conversational RAG endpoints.

Endpoints:
  POST   /chat                       — Non-streaming Q&A
  POST   /chat/stream                — SSE streaming Q&A
  GET    /chat/sessions              — List user sessions
  GET    /chat/sessions/{id}         — Session detail + message history
  DELETE /chat/sessions/{id}         — Delete session
  GET    /chat/sessions/{id}/citations — All citations for session
"""
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from typing import List
import uuid
import structlog

from app.schemas.responses import ApiResponse
from app.schemas.chat import (
    ChatRequest, ChatResponse, CitationResponse,
    SessionSummary, SessionDetailResponse, SessionCitationResponse,
    MessageResponse,
)
from app.services.chat_service import chat_service
from app.models.domain import User
from app.models.chat import ConversationSession, ChatMessage
from app.api.dependencies import get_db, get_current_user

router = APIRouter()
logger = structlog.get_logger(__name__)


# ---------------------------------------------------------------------------
# Chat Endpoints
# ---------------------------------------------------------------------------

@router.post(
    "/chat",
    response_model=ApiResponse[ChatResponse],
    status_code=status.HTTP_200_OK,
    summary="Ask a question to the AI Knowledge Assistant",
    description=(
        "Non-streaming RAG Q&A. Retrieves relevant context from the knowledge base, "
        "sends to LLM, and returns a grounded answer with source citations."
    ),
)
async def chat(
    request: ChatRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> ApiResponse[ChatResponse]:
    """Non-streaming conversational RAG endpoint."""
    try:
        result = await chat_service.chat(
            db=db,
            user_id=current_user.id,
            knowledge_base_id=request.knowledge_base_id,
            question=request.question,
            session_id=request.session_id,
        )
        return ApiResponse(data=ChatResponse(
            session_id=result.get("session_id"),
            answer=result["answer"],
            citations=[CitationResponse(**c) for c in result.get("citations", [])],
            model=result.get("model"),
            provider=result.get("provider"),
            latency_ms=result.get("latency_ms", 0),
            total_tokens=result.get("total_tokens", 0),
            safety_flagged=result.get("safety_flagged", False),
        ))
    except Exception as exc:
        logger.error("chat_endpoint_error", error=str(exc))
        raise HTTPException(status_code=500, detail=str(exc))


@router.post(
    "/chat/stream",
    summary="Stream a response from the AI Knowledge Assistant",
    description=(
        "SSE streaming RAG Q&A. Streams tokens as they are generated by the LLM. "
        "Final event includes citations and session metadata."
    ),
    response_class=StreamingResponse,
)
async def chat_stream(
    request: ChatRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> StreamingResponse:
    """
    SSE Streaming Q&A endpoint.
    Events format:
      data: {"token": "...", "done": false}
      data: {"done": true, "session_id": "...", "citations": [...]}
      data: [DONE]
    """
    async def generate():
        async for chunk in chat_service.chat_stream(
            db=db,
            user_id=current_user.id,
            knowledge_base_id=request.knowledge_base_id,
            question=request.question,
            session_id=request.session_id,
        ):
            yield chunk

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",   # Disable nginx buffering
            "Connection": "keep-alive",
        },
    )


# ---------------------------------------------------------------------------
# Session Management Endpoints
# ---------------------------------------------------------------------------

@router.get(
    "/chat/sessions",
    response_model=ApiResponse[List[SessionSummary]],
    summary="List conversation sessions",
)
async def list_sessions(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> ApiResponse[List[SessionSummary]]:
    """List all active sessions for the authenticated user."""
    sessions = await chat_service.list_sessions(db, current_user.id)
    return ApiResponse(data=[SessionSummary.model_validate(s) for s in sessions])


@router.get(
    "/chat/sessions/{session_id}",
    response_model=ApiResponse[SessionDetailResponse],
    summary="Get session with full message history",
)
async def get_session(
    session_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> ApiResponse[SessionDetailResponse]:
    """Get a conversation session with its complete message history."""
    session = await chat_service.get_session(db, session_id, current_user.id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    # Load messages
    result = await db.execute(
        select(ChatMessage)
        .where(ChatMessage.session_id == session_id)
        .order_by(ChatMessage.created_at.asc())
    )
    messages = list(result.scalars().all())

    response = SessionDetailResponse(
        id=session.id,
        title=session.title,
        knowledge_base_id=session.knowledge_base_id,
        llm_provider=session.llm_provider,
        llm_model=session.llm_model,
        total_messages=session.total_messages,
        total_tokens_used=session.total_tokens_used,
        messages=[MessageResponse.model_validate(m) for m in messages],
        created_at=session.created_at,
        updated_at=session.updated_at,
    )
    return ApiResponse(data=response)


@router.delete(
    "/chat/sessions/{session_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete a conversation session",
)
async def delete_session(
    session_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> None:
    """Soft-delete a conversation session and all its messages."""
    deleted = await chat_service.delete_session(db, session_id, current_user.id)
    if not deleted:
        raise HTTPException(status_code=404, detail="Session not found")


@router.get(
    "/chat/sessions/{session_id}/citations",
    response_model=ApiResponse[List[SessionCitationResponse]],
    summary="Get all citations for a session",
)
async def get_session_citations(
    session_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> ApiResponse[List[SessionCitationResponse]]:
    """Retrieve all source citations referenced in a conversation session."""
    citations = await chat_service.get_session_citations(db, session_id, current_user.id)
    return ApiResponse(data=[SessionCitationResponse.model_validate(c) for c in citations])
