"""Add RAG tables

Revision ID: 627b590411f8
Revises: 
Create Date: 2026-07-14 22:40:06.604673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '627b590411f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_knowledge_bases',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('index_path', sa.String(length=1024), nullable=True),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('rag_documents',
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['rag_knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_documents_knowledge_base_id'), 'rag_documents', ['knowledge_base_id'], unique=False)
    op.create_table('rag_indexes',
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('index_path', sa.String(length=1024), nullable=False),
    sa.Column('index_type', sa.String(length=50), nullable=False),
    sa.Column('embedding_model', sa.String(length=255), nullable=False),
    sa.Column('vector_dim', sa.Integer(), nullable=False),
    sa.Column('total_vectors', sa.Integer(), nullable=False),
    sa.Column('build_config', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['rag_knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_base_id')
    )
    op.create_table('rag_retrieval_logs',
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('retrieved_chunk_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['rag_knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_retrieval_logs_knowledge_base_id'), 'rag_retrieval_logs', ['knowledge_base_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('dataset_type', sa.String(length=50), nullable=False),
    sa.Column('file_format', sa.String(length=20), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('schema_info', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_name'), 'datasets', ['name'], unique=False)
    op.create_table('documents',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('s3_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mlflow_experiment_id', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_logs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('prediction_result', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_logs_model_name'), 'prediction_logs', ['model_name'], unique=False)
    op.create_index(op.f('ix_prediction_logs_project_id'), 'prediction_logs', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['rag_knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_chunks_document_id'), 'rag_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_knowledge_base_id'), 'rag_chunks', ['knowledge_base_id'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dl_training_jobs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('problem_type', sa.String(length=50), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('architecture', sa.String(length=100), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('current_epoch', sa.Integer(), nullable=False),
    sa.Column('total_epochs', sa.Integer(), nullable=False),
    sa.Column('best_val_loss', sa.Float(), nullable=True),
    sa.Column('best_epoch', sa.Integer(), nullable=True),
    sa.Column('checkpoint_dir', sa.String(length=1024), nullable=True),
    sa.Column('best_model_path', sa.String(length=1024), nullable=True),
    sa.Column('tensorboard_dir', sa.String(length=1024), nullable=True),
    sa.Column('metrics_history', sa.JSON(), nullable=True),
    sa.Column('final_metrics', sa.JSON(), nullable=True),
    sa.Column('mlflow_run_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dl_training_jobs_dataset_id'), 'dl_training_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dl_training_jobs_project_id'), 'dl_training_jobs', ['project_id'], unique=False)
    op.create_table('evaluation_jobs',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('problem_type', sa.String(length=50), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=True),
    sa.Column('leaderboard', sa.JSON(), nullable=True),
    sa.Column('best_algorithm', sa.String(length=100), nullable=True),
    sa.Column('best_metrics', sa.JSON(), nullable=True),
    sa.Column('best_model_path', sa.String(length=1024), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('preprocessing_pipeline_path', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_jobs_dataset_id'), 'evaluation_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_evaluation_jobs_project_id'), 'evaluation_jobs', ['project_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('s3_model_path', sa.String(length=1024), nullable=False),
    sa.Column('metrics', sa.String(), nullable=True),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preprocessing_reports',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_shape', sa.JSON(), nullable=True),
    sa.Column('output_shape', sa.JSON(), nullable=True),
    sa.Column('output_columns', sa.JSON(), nullable=True),
    sa.Column('pipeline_path', sa.String(length=1024), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preprocessing_reports_dataset_id'), 'preprocessing_reports', ['dataset_id'], unique=False)
    op.create_table('training_jobs',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('problem_type', sa.String(length=50), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('model_path', sa.String(length=1024), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('preprocessing_pipeline_path', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_jobs_dataset_id'), 'training_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_training_jobs_project_id'), 'training_jobs', ['project_id'], unique=False)
    op.create_table('validation_reports',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_reports_dataset_id'), 'validation_reports', ['dataset_id'], unique=False)
    op.create_table('predictions',
    sa.Column('input_data', sa.String(), nullable=False),
    sa.Column('output_data', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_index(op.f('ix_validation_reports_dataset_id'), table_name='validation_reports')
    op.drop_table('validation_reports')
    op.drop_index(op.f('ix_training_jobs_project_id'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_dataset_id'), table_name='training_jobs')
    op.drop_table('training_jobs')
    op.drop_index(op.f('ix_preprocessing_reports_dataset_id'), table_name='preprocessing_reports')
    op.drop_table('preprocessing_reports')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_evaluation_jobs_project_id'), table_name='evaluation_jobs')
    op.drop_index(op.f('ix_evaluation_jobs_dataset_id'), table_name='evaluation_jobs')
    op.drop_table('evaluation_jobs')
    op.drop_index(op.f('ix_dl_training_jobs_project_id'), table_name='dl_training_jobs')
    op.drop_index(op.f('ix_dl_training_jobs_dataset_id'), table_name='dl_training_jobs')
    op.drop_table('dl_training_jobs')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_rag_chunks_knowledge_base_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_document_id'), table_name='rag_chunks')
    op.drop_table('rag_chunks')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_prediction_logs_project_id'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_model_name'), table_name='prediction_logs')
    op.drop_table('prediction_logs')
    op.drop_table('experiments')
    op.drop_table('documents')
    op.drop_index(op.f('ix_datasets_name'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_rag_retrieval_logs_knowledge_base_id'), table_name='rag_retrieval_logs')
    op.drop_table('rag_retrieval_logs')
    op.drop_table('rag_indexes')
    op.drop_index(op.f('ix_rag_documents_knowledge_base_id'), table_name='rag_documents')
    op.drop_table('rag_documents')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('rag_knowledge_bases')
    # ### end Alembic commands ###
